export const institute_types = [
  {
    label: "University",
    value: "University",
  },
  {
    label: "College",
    value: "College",
  },
  {
    label: "Higher",
    value: "Higher",
  },
];

export const timezones = Intl.supportedValuesOf("timeZone");

export const currencies = [
  {
    value: "USD",
    label: "USD",
  },
  {
    value: "GBP",
    label: "GBP",
  },
  {
    value: "EUR",
    label: "EUR",
  },
  {
    value: "BTC",
    label: "BTC",
  },
  {
    value: "JPY",
    label: "JPY",
  },
];

export const reviewer_types = [
  { label: "Customer", value: "Customer" },
  { label: "Student", value: "Student" },
  { label: "Employee", value: "Employee" },
  { label: "Other", value: "Other" },
];

export const review_status = [
  { label: "Pending", value: "PENDING" },
  { label: "Approved", value: "APPROVED" },
  { label: "Blocked", value: "BLOCKED" },
];

export const INFO_REQUEST_TYPES = [
  { label: "Institute", value: "Institute" },
  { label: "Education", value: "Education" },
  { label: "Airplane", value: "InstituteAirplane" },
  { label: "Simulator", value: "InstituteSimulator" },
];

export const countries = [
  { code: "AD", label: "Andorra", phone: "376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Alland Islands", phone: "358" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "242",
  },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", label: "Cook Islands", phone: "682" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "CW", label: "Curacao", phone: "599" },
  { code: "CX", label: "Christmas Island", phone: "61" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "DM", label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FJ", label: "Fiji", phone: "679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  { code: "FO", label: "Faroe Islands", phone: "298" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "GD", label: "Grenada", phone: "1-473" },
  { code: "GE", label: "Georgia", phone: "995" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "GG", label: "Guernsey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Greenland", phone: "299" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "GR", label: "Greece", phone: "30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HT", label: "Haiti", phone: "509" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", label: "Iraq", phone: "964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaica", phone: "1-876" },
  { code: "JO", label: "Jordan", phone: "962" },
  {
    code: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", label: "Cambodia", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comoros", phone: "269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  { code: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KW", label: "Kuwait", phone: "965" },
  { code: "KY", label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", label: "Lebanon", phone: "961" },
  { code: "LC", label: "Saint Lucia", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", label: "Montenegro", phone: "382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolia", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "NC", label: "New Caledonia", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Norfolk Island", phone: "672" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niue", phone: "683" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "PF", label: "French Polynesia", phone: "689" },
  { code: "PG", label: "Papua New Guinea", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Poland", phone: "48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palau", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "Reunion", phone: "262" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RS", label: "Serbia", phone: "381" },
  { code: "RU", label: "Russian Federation", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SB", label: "Solomon Islands", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "SH", label: "Saint Helena", phone: "290" },
  { code: "SI", label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "South Sudan", phone: "211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", label: "El Salvador", phone: "503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", label: "Swaziland", phone: "268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", label: "Chad", phone: "235" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "TJ", label: "Tajikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turkey", phone: "90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    label: "Taiwan, Republic of China",
    phone: "886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Uganda", phone: "256" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", label: "Venezuela", phone: "58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", label: "Vietnam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis and Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "XK", label: "Kosovo", phone: "383" },
  { code: "YE", label: "Yemen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export const languages = [
  {
    code: "ab",
    name: "Abkhaz",
    nativeName: "аҧсуа",
  },
  {
    code: "aa",
    name: "Afar",
    nativeName: "Afaraf",
  },
  {
    code: "af",
    name: "Afrikaans",
    nativeName: "Afrikaans",
  },
  {
    code: "ak",
    name: "Akan",
    nativeName: "Akan",
  },
  {
    code: "sq",
    name: "Albanian",
    nativeName: "Shqip",
  },
  {
    code: "am",
    name: "Amharic",
    nativeName: "አማርኛ",
  },
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
  },
  {
    code: "an",
    name: "Aragonese",
    nativeName: "Aragonés",
  },
  {
    code: "hy",
    name: "Armenian",
    nativeName: "Հայերեն",
  },
  {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
  },
  {
    code: "av",
    name: "Avaric",
    nativeName: "авар мацӀ, магӀарул мацӀ",
  },
  {
    code: "ae",
    name: "Avestan",
    nativeName: "avesta",
  },
  {
    code: "ay",
    name: "Aymara",
    nativeName: "aymar aru",
  },
  {
    code: "az",
    name: "Azerbaijani",
    nativeName: "azərbaycan dili",
  },
  {
    code: "bm",
    name: "Bambara",
    nativeName: "bamanankan",
  },
  {
    code: "ba",
    name: "Bashkir",
    nativeName: "башҡорт теле",
  },
  {
    code: "eu",
    name: "Basque",
    nativeName: "euskara, euskera",
  },
  {
    code: "be",
    name: "Belarusian",
    nativeName: "Беларуская",
  },
  {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
  },
  {
    code: "bh",
    name: "Bihari",
    nativeName: "भोजपुरी",
  },
  {
    code: "bi",
    name: "Bislama",
    nativeName: "Bislama",
  },
  {
    code: "bs",
    name: "Bosnian",
    nativeName: "bosanski jezik",
  },
  {
    code: "br",
    name: "Breton",
    nativeName: "brezhoneg",
  },
  {
    code: "bg",
    name: "Bulgarian",
    nativeName: "български език",
  },
  {
    code: "my",
    name: "Burmese",
    nativeName: "ဗမာစာ",
  },
  {
    code: "ca",
    name: "Catalan; Valencian",
    nativeName: "Català",
  },
  {
    code: "ch",
    name: "Chamorro",
    nativeName: "Chamoru",
  },
  {
    code: "ce",
    name: "Chechen",
    nativeName: "нохчийн мотт",
  },
  {
    code: "ny",
    name: "Chichewa; Chewa; Nyanja",
    nativeName: "chiCheŵa, chinyanja",
  },
  {
    code: "zh",
    name: "Chinese",
    nativeName: "中文 (Zhōngwén), 汉语, 漢語",
  },
  {
    code: "cv",
    name: "Chuvash",
    nativeName: "чӑваш чӗлхи",
  },
  {
    code: "kw",
    name: "Cornish",
    nativeName: "Kernewek",
  },
  {
    code: "co",
    name: "Corsican",
    nativeName: "corsu, lingua corsa",
  },
  {
    code: "cr",
    name: "Cree",
    nativeName: "ᓀᐦᐃᔭᐍᐏᐣ",
  },
  {
    code: "hr",
    name: "Croatian",
    nativeName: "hrvatski",
  },
  {
    code: "cs",
    name: "Czech",
    nativeName: "česky, čeština",
  },
  {
    code: "da",
    name: "Danish",
    nativeName: "dansk",
  },
  {
    code: "dv",
    name: "Divehi; Dhivehi; Maldivian;",
    nativeName: "ދިވެހި",
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands, Vlaams",
  },
  {
    code: "en",
    name: "English",
    nativeName: "English",
  },
  {
    code: "eo",
    name: "Esperanto",
    nativeName: "Esperanto",
  },
  {
    code: "et",
    name: "Estonian",
    nativeName: "eesti, eesti keel",
  },
  {
    code: "ee",
    name: "Ewe",
    nativeName: "Eʋegbe",
  },
  {
    code: "fo",
    name: "Faroese",
    nativeName: "føroyskt",
  },
  {
    code: "fj",
    name: "Fijian",
    nativeName: "vosa Vakaviti",
  },
  {
    code: "fi",
    name: "Finnish",
    nativeName: "suomi, suomen kieli",
  },
  {
    code: "fr",
    name: "French",
    nativeName: "français, langue française",
  },
  {
    code: "ff",
    name: "Fula; Fulah; Pulaar; Pular",
    nativeName: "Fulfulde, Pulaar, Pular",
  },
  {
    code: "gl",
    name: "Galician",
    nativeName: "Galego",
  },
  {
    code: "ka",
    name: "Georgian",
    nativeName: "ქართული",
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
  },
  {
    code: "el",
    name: "Greek, Modern",
    nativeName: "Ελληνικά",
  },
  {
    code: "gn",
    name: "Guaraní",
    nativeName: "Avañeẽ",
  },
  {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
  },
  {
    code: "ht",
    name: "Haitian; Haitian Creole",
    nativeName: "Kreyòl ayisyen",
  },
  {
    code: "ha",
    name: "Hausa",
    nativeName: "Hausa, هَوُسَ",
  },
  {
    code: "he",
    name: "Hebrew (modern)",
    nativeName: "עברית",
  },
  {
    code: "hz",
    name: "Herero",
    nativeName: "Otjiherero",
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी, हिंदी",
  },
  {
    code: "ho",
    name: "Hiri Motu",
    nativeName: "Hiri Motu",
  },
  {
    code: "hu",
    name: "Hungarian",
    nativeName: "Magyar",
  },
  {
    code: "ia",
    name: "Interlingua",
    nativeName: "Interlingua",
  },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
  },
  {
    code: "ie",
    name: "Interlingue",
    nativeName: "Originally called Occidental; then Interlingue after WWII",
  },
  {
    code: "ga",
    name: "Irish",
    nativeName: "Gaeilge",
  },
  {
    code: "ig",
    name: "Igbo",
    nativeName: "Asụsụ Igbo",
  },
  {
    code: "ik",
    name: "Inupiaq",
    nativeName: "Iñupiaq, Iñupiatun",
  },
  {
    code: "io",
    name: "Ido",
    nativeName: "Ido",
  },
  {
    code: "is",
    name: "Icelandic",
    nativeName: "Íslenska",
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
  },
  {
    code: "iu",
    name: "Inuktitut",
    nativeName: "ᐃᓄᒃᑎᑐᑦ",
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語 (にほんご／にっぽんご)",
  },
  {
    code: "jv",
    name: "Javanese",
    nativeName: "basa Jawa",
  },
  {
    code: "kl",
    name: "Kalaallisut, Greenlandic",
    nativeName: "kalaallisut, kalaallit oqaasii",
  },
  {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
  },
  {
    code: "kr",
    name: "Kanuri",
    nativeName: "Kanuri",
  },
  {
    code: "ks",
    name: "Kashmiri",
    nativeName: "कश्मीरी, كشميري‎",
  },
  {
    code: "kk",
    name: "Kazakh",
    nativeName: "Қазақ тілі",
  },
  {
    code: "km",
    name: "Khmer",
    nativeName: "ភាសាខ្មែរ",
  },
  {
    code: "ki",
    name: "Kikuyu, Gikuyu",
    nativeName: "Gĩkũyũ",
  },
  {
    code: "rw",
    name: "Kinyarwanda",
    nativeName: "Ikinyarwanda",
  },
  {
    code: "ky",
    name: "Kirghiz, Kyrgyz",
    nativeName: "кыргыз тили",
  },
  {
    code: "kv",
    name: "Komi",
    nativeName: "коми кыв",
  },
  {
    code: "kg",
    name: "Kongo",
    nativeName: "KiKongo",
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어 (韓國語), 조선말 (朝鮮語)",
  },
  {
    code: "ku",
    name: "Kurdish",
    nativeName: "Kurdî, كوردی‎",
  },
  {
    code: "kj",
    name: "Kwanyama, Kuanyama",
    nativeName: "Kuanyama",
  },
  {
    code: "la",
    name: "Latin",
    nativeName: "latine, lingua latina",
  },
  {
    code: "lb",
    name: "Luxembourgish, Letzeburgesch",
    nativeName: "Lëtzebuergesch",
  },
  {
    code: "lg",
    name: "Luganda",
    nativeName: "Luganda",
  },
  {
    code: "li",
    name: "Limburgish, Limburgan, Limburger",
    nativeName: "Limburgs",
  },
  {
    code: "ln",
    name: "Lingala",
    nativeName: "Lingála",
  },
  {
    code: "lo",
    name: "Lao",
    nativeName: "ພາສາລາວ",
  },
  {
    code: "lt",
    name: "Lithuanian",
    nativeName: "lietuvių kalba",
  },
  {
    code: "lu",
    name: "Luba-Katanga",
    nativeName: "",
  },
  {
    code: "lv",
    name: "Latvian",
    nativeName: "latviešu valoda",
  },
  {
    code: "gv",
    name: "Manx",
    nativeName: "Gaelg, Gailck",
  },
  {
    code: "mk",
    name: "Macedonian",
    nativeName: "македонски јазик",
  },
  {
    code: "mg",
    name: "Malagasy",
    nativeName: "Malagasy fiteny",
  },
  {
    code: "ms",
    name: "Malay",
    nativeName: "bahasa Melayu, بهاس ملايو‎",
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
  },
  {
    code: "mt",
    name: "Maltese",
    nativeName: "Malti",
  },
  {
    code: "mi",
    name: "Māori",
    nativeName: "te reo Māori",
  },
  {
    code: "mr",
    name: "Marathi (Marāṭhī)",
    nativeName: "मराठी",
  },
  {
    code: "mh",
    name: "Marshallese",
    nativeName: "Kajin M̧ajeļ",
  },
  {
    code: "mn",
    name: "Mongolian",
    nativeName: "монгол",
  },
  {
    code: "na",
    name: "Nauru",
    nativeName: "Ekakairũ Naoero",
  },
  {
    code: "nv",
    name: "Navajo, Navaho",
    nativeName: "Diné bizaad, Dinékʼehǰí",
  },
  {
    code: "nb",
    name: "Norwegian Bokmål",
    nativeName: "Norsk bokmål",
  },
  {
    code: "nd",
    name: "North Ndebele",
    nativeName: "isiNdebele",
  },
  {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
  },
  {
    code: "ng",
    name: "Ndonga",
    nativeName: "Owambo",
  },
  {
    code: "nn",
    name: "Norwegian Nynorsk",
    nativeName: "Norsk nynorsk",
  },
  {
    code: "no",
    name: "Norwegian",
    nativeName: "Norsk",
  },
  {
    code: "ii",
    name: "Nuosu",
    nativeName: "ꆈꌠ꒿ Nuosuhxop",
  },
  {
    code: "nr",
    name: "South Ndebele",
    nativeName: "isiNdebele",
  },
  {
    code: "oc",
    name: "Occitan",
    nativeName: "Occitan",
  },
  {
    code: "oj",
    name: "Ojibwe, Ojibwa",
    nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  },
  {
    code: "cu",
    name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
    nativeName: "ѩзыкъ словѣньскъ",
  },
  {
    code: "om",
    name: "Oromo",
    nativeName: "Afaan Oromoo",
  },
  {
    code: "or",
    name: "Oriya",
    nativeName: "ଓଡ଼ିଆ",
  },
  {
    code: "os",
    name: "Ossetian, Ossetic",
    nativeName: "ирон æвзаг",
  },
  {
    code: "pa",
    name: "Panjabi, Punjabi",
    nativeName: "ਪੰਜਾਬੀ, پنجابی‎",
  },
  {
    code: "pi",
    name: "Pāli",
    nativeName: "पाऴि",
  },
  {
    code: "fa",
    name: "Persian",
    nativeName: "فارسی",
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "polski",
  },
  {
    code: "ps",
    name: "Pashto, Pushto",
    nativeName: "پښتو",
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
  },
  {
    code: "qu",
    name: "Quechua",
    nativeName: "Runa Simi, Kichwa",
  },
  {
    code: "rm",
    name: "Romansh",
    nativeName: "rumantsch grischun",
  },
  {
    code: "rn",
    name: "Kirundi",
    nativeName: "kiRundi",
  },
  {
    code: "ro",
    name: "Romanian, Moldavian, Moldovan",
    nativeName: "română",
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "русский язык",
  },
  {
    code: "sa",
    name: "Sanskrit (Saṁskṛta)",
    nativeName: "संस्कृतम्",
  },
  {
    code: "sc",
    name: "Sardinian",
    nativeName: "sardu",
  },
  {
    code: "sd",
    name: "Sindhi",
    nativeName: "सिन्धी, سنڌي، سندھی‎",
  },
  {
    code: "se",
    name: "Northern Sami",
    nativeName: "Davvisámegiella",
  },
  {
    code: "sm",
    name: "Samoan",
    nativeName: "gagana faa Samoa",
  },
  {
    code: "sg",
    name: "Sango",
    nativeName: "yângâ tî sängö",
  },
  {
    code: "sr",
    name: "Serbian",
    nativeName: "српски језик",
  },
  {
    code: "gd",
    name: "Scottish Gaelic; Gaelic",
    nativeName: "Gàidhlig",
  },
  {
    code: "sn",
    name: "Shona",
    nativeName: "chiShona",
  },
  {
    code: "si",
    name: "Sinhala, Sinhalese",
    nativeName: "සිංහල",
  },
  {
    code: "sk",
    name: "Slovak",
    nativeName: "slovenčina",
  },
  {
    code: "sl",
    name: "Slovene",
    nativeName: "slovenščina",
  },
  {
    code: "so",
    name: "Somali",
    nativeName: "Soomaaliga, af Soomaali",
  },
  {
    code: "st",
    name: "Southern Sotho",
    nativeName: "Sesotho",
  },
  {
    code: "es",
    name: "Spanish; Castilian",
    nativeName: "español, castellano",
  },
  {
    code: "su",
    name: "Sundanese",
    nativeName: "Basa Sunda",
  },
  {
    code: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
  },
  {
    code: "ss",
    name: "Swati",
    nativeName: "SiSwati",
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "svenska",
  },
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
  },
  {
    code: "tg",
    name: "Tajik",
    nativeName: "тоҷикӣ, toğikī, تاجیکی‎",
  },
  {
    code: "th",
    name: "Thai",
    nativeName: "ไทย",
  },
  {
    code: "ti",
    name: "Tigrinya",
    nativeName: "ትግርኛ",
  },
  {
    code: "bo",
    name: "Tibetan Standard, Tibetan, Central",
    nativeName: "བོད་ཡིག",
  },
  {
    code: "tk",
    name: "Turkmen",
    nativeName: "Türkmen, Түркмен",
  },
  {
    code: "tl",
    name: "Tagalog",
    nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
  },
  {
    code: "tn",
    name: "Tswana",
    nativeName: "Setswana",
  },
  {
    code: "to",
    name: "Tonga (Tonga Islands)",
    nativeName: "faka Tonga",
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
  },
  {
    code: "ts",
    name: "Tsonga",
    nativeName: "Xitsonga",
  },
  {
    code: "tt",
    name: "Tatar",
    nativeName: "татарча, tatarça, تاتارچا‎",
  },
  {
    code: "tw",
    name: "Twi",
    nativeName: "Twi",
  },
  {
    code: "ty",
    name: "Tahitian",
    nativeName: "Reo Tahiti",
  },
  {
    code: "ug",
    name: "Uighur, Uyghur",
    nativeName: "Uyƣurqə, ئۇيغۇرچە‎",
  },
  {
    code: "uk",
    name: "Ukrainian",
    nativeName: "українська",
  },
  {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
  },
  {
    code: "uz",
    name: "Uzbek",
    nativeName: "zbek, Ўзбек, أۇزبېك‎",
  },
  {
    code: "ve",
    name: "Venda",
    nativeName: "Tshivenḓa",
  },
  {
    code: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
  },
  {
    code: "vo",
    name: "Volapük",
    nativeName: "Volapük",
  },
  {
    code: "wa",
    name: "Walloon",
    nativeName: "Walon",
  },
  {
    code: "cy",
    name: "Welsh",
    nativeName: "Cymraeg",
  },
  {
    code: "wo",
    name: "Wolof",
    nativeName: "Wollof",
  },
  {
    code: "fy",
    name: "Western Frisian",
    nativeName: "Frysk",
  },
  {
    code: "xh",
    name: "Xhosa",
    nativeName: "isiXhosa",
  },
  {
    code: "yi",
    name: "Yiddish",
    nativeName: "ייִדיש",
  },
  {
    code: "yo",
    name: "Yoruba",
    nativeName: "Yorùbá",
  },
  {
    code: "za",
    name: "Zhuang, Chuang",
    nativeName: "Saɯ cueŋƅ, Saw cuengh",
  },
];
